### ISSUE TITLE
easy way to resolve name conflicts with namespaced model classes?

### ISSUE THREAD

**Issue by jaydanielian** [fotinakis/swagger-blocks#13]
I have a scenario where I have two classes named SearchRequest. They are in different module namespaces however.  But when the documentation is generated, it only outputs the last version of the SearchRequest class - thus outputting incorrect documentation on one of my endpoints.

Is there anyway in the parameter to specify a more specific symbol?

Right now I have this => 
   parameter do
              key :paramType, :body
              key :name, :body
              key :description, 'Report body which includes an array of match_requests'
              key :required, true
              key :type, :SearchRequest
            end

which obviously isn't specific enough.

Ideally something like this would work => 
   parameter do
              key :paramType, :body
              key :name, :body
              key :description, 'Report body which includes an array of match_requests'
              key :required, true
              key :type, 'ModuleName::SearchRequest'
            end

and it would be smart enough to know where to find that class. 

This is a great tool, and I have generated all my documentation with it, but I found that one little issue that I would love to know how to resolve. From my tracing it seems like it is an issue with this merge! call in self.build_api_json for the models. Because the underlying hash takes the class name (from the symbol), the merge! clobbers the initial item in the hash. That is my guess at what is happening - and I unfortunately don't know how to resolve it. 

Any ideas would be great. Thanks!

**Comment by fotinakis** [comment]
Glad you're finding this project useful!

Good question—I think the answer is not actually swagger-blocks related: the swagger spec itself has a single flat namespace for model definitions ("schemas" in swagger 2.0). So, the way we interpret this in swagger-blocks is to just take the name you give—by which I mean, the name of the swagger model itself has nothing to do with a Ruby module or class name, it has everything to do with what name you specify. For example:

In swagger 1.2:

```ruby
swagger_model : SearchRequest do
  key :id, :SearchRequest
end
```

Or in swagger 2.0:
```ruby
swagger_schema :SearchRequest do
  # ...
end
```

That `SearchRequest` is the name of the model, and by design we merge all internal definitions wrapped by the same model name since there is only namespace in Swagger-land—so that is why you see it get overwritten. AFAIK in swagger's design, there is no way to represent models in different namespaces, you simply have to name them differently. Again, the Ruby class can be named the same, and you can independently give the swagger schemas different names. Also you might try a string there instead of a symbol, in which case you could use `'ModuleName::SearchRequest'` as long as Swagger UI doesn't have a problem with that model name.

Does that answer your question? Feel free to comment or re-open if you think there's some better way we can address this in swagger-blocks.

**Comment by jaydanielian** [comment]
Thanks for that explanation - that really helps. I am still relatively new to Ruby, but the community never ceases to amaze me with the responses, help, etc. Such a breath of fresh air.  

Thanks again!

J
