### ISSUE TITLE
How do you add parameters to formData payload ?

### ISSUE THREAD

**Issue by josephmisiti** [fotinakis/swagger-blocks#16]
I have a post call, I am trying to add parameters to `formdata` with no success

**Comment by fotinakis** [comment]
Can you give a bit more info? What do your swagger-blocks definitions look like and how are they not working?

**Comment by josephmisiti** [comment]
here is an example 

```ruby
      swagger_path '/sessions' do
        operation :post do
          key :description, 'Login To Vestorly Platform'
          key :operationId, 'login'
          key :consumes, [
            "application/x-www-form-urlencoded"
          ]
          key :tags, [
            'session'
          ]
          parameter do
            key :name, :username
            key :in, :formData
            key :description, 'Username in the XXXX platform'
            key :required, true
            key :type, :string
          end
      
          parameter do
            key :name, :password
            key :in, :formData
            key :description, 'Password in XXXX Platform'
            key :required, true
            key :type, :string
          end
  
          response 200 do
            key :description, 'Response'
            schema do
              key :'$ref', :Session
            end
          end
        end
      end
```

Here is the call that works in CURL:

```
curl -X POST https://www.example.com/api/v2/sessions
  -d "username=USERNAME"
  -d "password=PASSWORD"
```

I cannot get swagger-blocks to send those username + password parameters in the post

**Comment by josephmisiti** [comment]
also according to swaggers 2.0 spec, you can use the `:formData` parameter:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md

**Comment by fotinakis** [comment]
That looks correct to me, except I don't understand what you mean by "get swagger-blocks to send those username + password parameters in the post"—Swagger::Blocks doesn't send anything, it's simply a way to define JSON in the Swagger style, for example as input to [Swagger UI](https://github.com/swagger-api/swagger-ui) for generating API docs—it has nothing to do with actually how your server handles data.

If the output of your `/apidocs` endpoint (see main README) is incorrect, that's something I can help you with, but otherwise it sounds unrelated to swagger-blocks. Closing for now, but feel free to comment with more info if you think it is actually swagger-blocks related.

**Comment by josephmisiti** [comment]
Sorry - I see why that is confusing. I meant when I generate swagger.json
and try to use this method in Swagger UI, the post does not send formdata.

**Comment by fotinakis** [comment]
Can you check that the swagger.json looks correct according to the spec and maybe manually fiddle with it until it works with Swagger UI the way you expect? Unfortunately this sounds like you're just missing some part of the configuration between Swagger JSON and Swagger UI, but not actually a problem with how swagger-blocks generates JSON.

**Comment by josephmisiti** [comment]
the issue was with `swagger-ui`: https://github.com/swagger-api/swagger-ui/issues/838

sorry for wasting your time :)

**Comment by fotinakis** [comment]
Not a waste, glad you found it. :+1:
