### ISSUE TITLE
Can't add a root node for a body param?

### ISSUE THREAD

**Issue by claude** [fotinakis/swagger-blocks#3]
Not sure if this is a problem with swagger-blocks or swagger itself, but I'm having a hard time finding any answers out there.

Let's say I have a create action for a Blog controller and I have a Blog model. In my swagger_api_root block for the create action there is one param of paramType "body" and of type "Blog" that matches the model reference. When I view this in the swagger-UI it allows me to pre-populate the body with something like this when I click on the model schema:

```json
{ 
  "id": "integer",
  "author_id": "integer",
  "body": "text",
  "title": "string"
}
```
unfortunately this isn't what is expected on the back end. 
It should be something like this:

```json
{ "blog": 
  { 
    "id": "integer",
    "author_id": "integer",
    "body": "text",
    "title": "string"
  }
}
```

I know rails does some auto-magical stuff to add these to a "blog" param, but only if the params are sent in snake_case, not camelCase. If you change author_id to authorId, it is left out of the body param. I'm trying to cater our API to javascript developers and support both camelCase and snake_case and would like the documentation in swagger to reference the camelCase params. 

Any idea how to accomplish this? Any help would be appreciated.

**Comment by fotinakis** [comment]
I believe what you're referencing is two things that are not really swagger-blocks issues: 1) that Rails usually expects controllers to receive params with a wrapping hash, like the `{"post": {"id": 1}}` form (ie. Rails helpers like `form_for` generate HTML like `<input name="person[first_name]">` and controllers parse this out into `params` that way), and 2) that Swagger doesn't make any assumptions like this, it simply presents what you give it.

I'm sure you can build your swagger models to present the wrapped format, maybe something like this (totally untested code follows):

```ruby
swagger_model :Post do
  key :id, :Post
  property :title do
    key :type, :string
  end
  property :body do
    key :type, :string
  end
end

swagger_model :PostRequest do
  key :id, :PostRequest
  property :post do
    key :'$ref', :Post
  end
end

swagger_model :PostResponse do
  key :id, :Post
  property :post do
    key :'$ref', :Post
  end
  # Other properties side-loaded in the response here, like "comments", "users" etc.
end

swagger_model :PostsResponse do
  key :id, :Post
  property :tags do
    key :type, :array
    items do
      key :'$ref', :Post
    end
  end
  # Other properties side-loaded in the response here, like "comments", "users" etc.
end
```

So, you'd use the `:PostRequest` type any time you expect the `{"post": {"id": 1}}` format, the `:PostResponse` for API responses in the same format, `:PostsResponse` for responses with multiple objects, like `{"posts": [{"id": 1}, {"id": 2}}`, etc. Just create wrapper models and reference those in `swagger_api_root ` definitions instead of `:Post` directly.

Also, I'd avoid building an API that supports both camelCase and snake_case naming—pick one or the other and document it that way, or you'll complicate your life quite a bit. :) There are javascript libraries and frameworks that have translation adapters for exactly these reasons (for example, if you're using Ember there is [DS.ActiveModelAdapter](http://emberjs.com/api/data/classes/DS.ActiveModelAdapter.html)).

Let me know if that style works and I'll add something to the README. I'll consider this issues closed since it's not really swagger-blocks related. Thanks!

**Comment by claude** [comment]
Thanks for the feedback. Yes, this style works. I suppose if this were a rails specific gem there could be a better way to generate this with less code, but keeping this general purpose makes sense.
