### ISSUE TITLE
Set the host attribute dynamically

### ISSUE THREAD

**Issue by akaragkiozidis** [fotinakis/swagger-blocks#30]
Some APIs require a different host on some circumstances (for example, each account in an application has its own subdomain)

```
winterfell.lvh.me:3000/api
castleblack.lvh.me:3000/api
etc.
```

I believe it would be a nice enhancement to set the host with an optional parameter when building the root JSON. I was considering something like:

```
def index
  render json: Swagger::Blocks.build_root_json(SWAGGERED_CLASSES, {subdomain: 'winterfell'})  
end
```

```
def self.build_root_json(swaggered_classes, options = {})
  data = Swagger::Blocks::InternalHelpers.parse_swaggered_classes(swaggered_classes)

  if data[:root_node].is_swagger_2_0?
    data[:root_node].key(:paths, data[:path_nodes]) # Required, so no empty check.
    if data[:schema_nodes] && !data[:schema_nodes].empty?
      data[:root_node].key(:definitions, data[:schema_nodes])
    end
  end

  # Subdomain is prepended here
  if options[:subdomain].present?
    data[:root_node].data[:host] = "#{options[:subdomain]}.#{data[:root_node].data[:host]}"
  end

  data[:root_node].as_json
end
```

@fotinakis what do you think? Can you think of a different approach? I could work on a pull request for this but it would be nice to agree on this first. :)

**Comment by fotinakis** [comment]
@akaragkiozidis Thanks for opening an issue to chat before a PR. :)

I've thought about handling these kinds of things by just globally allowing `key` to take a lambda/proc like `key :host, -> { dynamic_thing }`, but I don't think it works because because Swagger::Blocks is totally class-scoped and has no understanding of the current instance (there might not even be an instance). The solution you posted, though nice, is pretty specific to your use-case of dynamic subdomains—I'd like to find something that's a bit more generic.

I see three options:
- 1) Add a `host` arg to build_root_json (instead of subdomain, just allow overriding the whole thing).
- 2) Add an `overrides` arg to build_root_json (a hash, gets merged over the final JSON, lets people override anything for different contexts).
- 3) Just ask people to wrap build_root_json into their own method and do these customizations there.

I think I lean more toward # 3, what do you think?

**Comment by akaragkiozidis** [comment]
To be honest, I also thought that my solution was too specific, hence the issue.

If I understood correctly, # 3 would look sth like this:

```
def build_and_override_json(overrides = {})
  Swagger::Blocks.build_root_json(SWAGGERED_CLASSES).merge(overrides)
end
```

I also agree to this, it's much simpler and keeps the gem code intact. 

Although we are talking about just a JSON merge operation, it would be nice to add this on the README.md as a proposed practice.

**Comment by fotinakis** [comment]
Nice! That looks like a simple solution and keeps the responsibility for these customizations out of the gem. Going to close this as fixed.
