### ISSUE TITLE
Items block in a Parameter, supported?

### ISSUE THREAD

**Issue by claude** [fotinakis/swagger-blocks#4]
So pardon my noobiness, just started playing with swagger so I'm not 100% sure if this is the way things are done, but I wanted to define a parameter as type array and then specify the type using an items block. 

```ruby
parameter do
  key :paramType, :query
  key :name, :recipients
  key :description, 'list of profile_ids that should receive the message'
  key :required, true
  key :type, :array
  items do
    key :type, :uuid
  end
end
```

when I try that I get:
```ruby
undefined method `items' for #<Swagger::Blocks::ParameterNode:0x007fb3e0b9d0c0>:
```

I know I can make a model to define the param type, but shouldn't this work?

**Comment by fotinakis** [comment]
Swagger doesn't support "type" or "items" in [Parameter objects](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#524-parameter-object) — because HTTP doesn't either, the fact that you can do `recipients[]=1&recipients[]=2` and get an array in the controller is purely a Rails construct.

So, you could probably do this (untested code follows), just name the parameter "recipients[]" and maybe explain in the description how to send it:

```ruby
parameter do
  key :paramType, :query
  key :name, 'recipients[]'
  key :description, 'list of profile_ids that should receive the message'
  key :required, true
end
```

**Comment by claude** [comment]
Thanks Mike, makes sense.

**Comment by fotinakis** [comment]
:+1:
