### ISSUE TITLE
Proposal : SemVer

### ISSUE THREAD

**Issue by whistlerbrk** [fotinakis/swagger-blocks#47]
To eliminate some confusion as to compatibility with the overall Swagger Spec and the versioning of the gem itself.

**Comment by fotinakis** [comment]
We already follow semantic versioning. You mean you want us to sync swagger-blocks versioning with Swagger versions? That wouldn't work, because we want to be able to make and version differences in this library's functionality independent of the Swagger spec (which doesn't change that often). I think the version information in the Readme is very clear, no?

**Comment by whistlerbrk** [comment]
Yes, with swagger versions is how I'd meant. That would be the major and minor version of swagger-blocks corresponds to the major and minor versions of the Swagger spec. Perhaps you're right though. I'll close.
