### ISSUE TITLE
Reduce Hardcoding

### ISSUE THREAD

**Issue by ayudemura** [fotinakis/swagger-blocks#71]
When I have shown this gem to my team, first thing it was pointed out was that some hardcoding on documentation *should/could* be omitted.

For instance for `StudentsController`:
``` ruby
swagger_path '/students/{id}' do
  operation :get do
    key :description, 'Returns a single student'
    key :operationId, 'get_student_id'
    key :tags, [
      'student'
    ]
    :
  end
end
```
The `operatonId` could be the combination of `operation method` and `path`.
The `tags` could be model name of the `swaggered class` (`StudentsController`).
Currently, the operation node doesn't hold information of operation method, path, nor swaggered class, it is impossible to do so programmatically.

**Comment by fotinakis** [comment]
Ah I see. This is actually done by design — it is part of this philosophy from the readme: "1:1 naming with the Swagger spec—block names and nesting should match almost exactly with the swagger spec, with rare exceptions to make things more convenient."

We have intentionally not added many "combined" methods by design—though they are shorter, it then becomes a custom DSL that does not match Swagger itself, so you would have to look up _our_ way of doing it, rather than the Swagger spec way. This introduces complexity on our end for maintaining this gem (in our spare time), and also complexity for users because they have to figure out our custom implementation. So, this is an intentional design decision, even though it makes things more verbose. We have added "inline keys" as one way to make things shorter: https://github.com/fotinakis/swagger-blocks#inline-keys

Hope that makes sense!

**Comment by ayudemura** [comment]
ok, I understand the direction you are heading.  I am closing this issue then.
